llm:
  model: "gpt-4o-mini"
  temp: 0.001
  prompt: prompts/trial4.txt

search_kwargs:
  k: 15

chroma:
  persist_directory: "./chroma_persist"

text_splitter:
  chunk_size: 1300
  chunk_overlap: 200
